<?php

// prevent cross site request forgery
// generate token
// check exists validate
// delete token


class Token {

	public static function generate() {
		return Session::put(Config::get('session/token_name'), md5(uniqid()));
	}//this will generate a unique token with every session that is generated by the user (change when reload page)

	public static function check($token) {
		$tokenName = Config::get('session/token_name');

		if (Session::exists($tokenName) && $token === Session::get($tokenName)) {
			Session::delete($tokenName);//dont need it any more
			return true;
		}

		return false;
	}

}